### ISSUE TITLE
Use rustup instead of custom PS script

### ISSUE THREAD

**Issue by Arnavion** [starkat99/appveyor-rust#2]
Something like [this,](https://github.com/seanmonstar/reqwest/blob/677c1cca79896fdfacc92f6019a09726108e2788/.appveyor.yml#L8-L10) though I would change it to use `%USERPROFILE%` instead of `C:\Users\appveyor` when setting `PATH`

**Comment by starkat99** [comment]
Yup, I've been waiting for Rustup to stabilize, so now that it has, I've updated the configuration and removed the script!
